In [7]:
import pandas as pd


In [8]:
Claimant_df=pd.read_csv("claimants.csv")

In [9]:
Claimant_df

CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

In [10]:
Claimant_df.shape

(1340, 7)

In [11]:
Claimant_df.dtypes

CASENUM       int64
ATTORNEY      int64
CLMSEX      float64
CLMINSUR    float64
SEATBELT    float64
CLMAGE      float64
LOSS        float64
dtype: object

In [12]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [13]:
Claimant_df.describe(include="all")

CASENUM     ATTORNEY       CLMSEX     CLMINSUR     SEATBELT  \
count   1340.000000  1340.000000  1328.000000  1299.000000  1292.000000   
mean   11202.001493     0.488806     0.558735     0.907621     0.017028   
std     9512.750796     0.500061     0.496725     0.289671     0.129425   
min        0.000000     0.000000     0.000000     0.000000     0.000000   
25%     4177.000000     0.000000     0.000000     1.000000     0.000000   
50%     8756.500000     0.000000     1.000000     1.000000     0.000000   
75%    15702.500000     1.000000     1.000000     1.000000     0.000000   
max    34153.000000     1.000000     1.000000     1.000000     1.000000   

            CLMAGE         LOSS  
count  1151.000000  1340.000000  
mean     28.414422     3.806307  
std      20.304451    10.636903  
min       0.000000     0.000000  
25%       9.000000     0.400000  
50%      30.000000     1.069500  
75%      43.000000     3.781500  
max      95.000000   173.604000

In [14]:
Claimant_df.isna()

CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE   LOSS
0       False     False   False     False     False   False  False
1       False     False   False     False     False   False  False
2       False     False   False     False     False   False  False
3       False     False   False     False     False   False  False
4       False     False   False     False     False   False  False
...       ...       ...     ...       ...       ...     ...    ...
1335    False     False   False     False     False    True  False
1336    False     False   False     False     False   False  False
1337    False     False   False     False     False   False  False
1338    False     False   False     False     False   False  False
1339    False     False   False     False     False   False  False

[1340 rows x 7 columns]

In [15]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [16]:
Claimant_df['CLMSEX'].unique()

array([ 0.,  1., nan])

In [17]:
Claimant_df['CLMSEX']=Claimant_df['CLMSEX'].fillna(1)

In [18]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [19]:
Claimant_df['CLMINSUR'].unique()

array([ 1.,  0., nan])

In [20]:
Claimant_df['CLMINSUR']=Claimant_df['CLMINSUR'].fillna(1)

In [21]:
Claimant_df.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX        0
CLMINSUR      0
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [22]:
Claimant_df['SEATBELT'].unique()

array([ 0.,  1., nan])

In [23]:
Claimant_df['SEATBELT']=Claimant_df['SEATBELT'].fillna(1)

In [24]:
Claimant_df['CLMAGE']

0       50.0
1       18.0
2        5.0
3       31.0
4       30.0
        ... 
1335     NaN
1336    46.0
1337    39.0
1338     8.0
1339    30.0
Name: CLMAGE, Length: 1340, dtype: float64

In [25]:
Claimant_df['CLMAGE'].mean()

np.float64(28.414422241529106)

In [26]:
Claimant_df['CLMAGE']=Claimant_df['CLMAGE'].fillna(Claimant_df['CLMAGE'].mean())

In [27]:
Claimant_df['CLMAGE']

0       50.000000
1       18.000000
2        5.000000
3       31.000000
4       30.000000
          ...    
1335    28.414422
1336    46.000000
1337    39.000000
1338     8.000000
1339    30.000000
Name: CLMAGE, Length: 1340, dtype: float64

In [28]:
Claimant_df.isna().sum()

CASENUM     0
ATTORNEY    0
CLMSEX      0
CLMINSUR    0
SEATBELT    0
CLMAGE      0
LOSS        0
dtype: int64

In [29]:
x=Claimant_df.drop(labels="ATTORNEY",axis=1)

In [30]:
x

CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
0           5     0.0       1.0       0.0  50.000000  34.940
1           3     1.0       0.0       0.0  18.000000   0.891
2          66     0.0       1.0       0.0   5.000000   0.330
3          70     0.0       1.0       1.0  31.000000   0.037
4          96     0.0       1.0       0.0  30.000000   0.038
...       ...     ...       ...       ...        ...     ...
1335    34100     0.0       1.0       0.0  28.414422   0.576
1336    34110     1.0       1.0       0.0  46.000000   3.705
1337    34113     1.0       1.0       0.0  39.000000   0.099
1338    34145     1.0       0.0       0.0   8.000000   3.177
1339    34153     1.0       1.0       0.0  30.000000   0.688

[1340 rows x 6 columns]

In [31]:
y=Claimant_df["ATTORNEY"]

In [32]:
y

0       0
1       1
2       1
3       0
4       1
       ..
1335    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1340, dtype: int64

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.80,shuffle=True,random_state=10)

In [35]:
x_train

CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE    LOSS
782     10070     1.0       1.0       0.0   9.000000   0.680
414       575     0.0       1.0       0.0  14.000000   4.916
997     15574     0.0       0.0       0.0  28.414422   3.065
907     13385     0.0       1.0       0.0  39.000000   8.815
329      8418     1.0       1.0       0.0   6.000000   5.049
...       ...     ...       ...       ...        ...     ...
1180    30436     0.0       1.0       0.0  28.414422   0.098
1147    19410     0.0       0.0       0.0  51.000000  40.574
527      3748     0.0       1.0       0.0  28.414422   0.005
1149    19446     1.0       1.0       1.0   7.000000   0.156
1289    33073     1.0       1.0       0.0  41.000000   5.600

[1072 rows x 6 columns]

In [36]:
x_test

CASENUM  CLMSEX  CLMINSUR  SEATBELT     CLMAGE   LOSS
773      9903     0.0       1.0       0.0  28.414422  4.395
1088    17945     1.0       1.0       0.0   3.000000  0.346
301      7769     1.0       0.0       0.0  28.414422  0.008
383      9608     1.0       1.0       0.0  41.000000  1.306
318      8174     1.0       1.0       0.0  28.414422  0.050
...       ...     ...       ...       ...        ...    ...
104      1309     0.0       1.0       0.0   7.000000  0.589
672      7550     1.0       0.0       0.0  33.000000  0.000
1309    33590     0.0       1.0       0.0  30.000000  3.034
558      4404     0.0       1.0       0.0  57.000000  4.996
307      7904     0.0       1.0       0.0  57.000000  0.500

[268 rows x 6 columns]

In [37]:
y_train

782     0
414     0
997     1
907     0
329     1
       ..
1180    1
1147    0
527     0
1149    0
1289    0
Name: ATTORNEY, Length: 1072, dtype: int64

In [43]:
from sklearn.linear_model import LogisticRegression

In [46]:
model=LogisticRegression()

In [47]:
model.fit(x_train,y_train)

C:\Users\kalya\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [48]:
y_train_pred=model.predict(x_train)

In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [54]:
accuracy_score(y_train,y_train_pred)

0.710820895522388

In [55]:
y_test_pred=model.predict(x_test)

In [56]:
accuracy_score(y_test,y_test_pred)

0.7014925373134329

In [57]:
confusion_matrix(y_test,y_test_pred)

array([[ 78,  42],
       [ 38, 110]])

In [58]:
precision_score(y_test,y_test_pred)

0.7236842105263158

In [59]:
recall_score(y_test,y_test_pred)

0.7432432432432432